apiVersion: v1
kind: Service
metadata:
  name: smart-service-nodeport
spec:
  type: NodePort
  selector:
    app: smart-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001 # Fixed NodePort for easier access
